# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main

pool: Default

steps:
- checkout: self

- script: echo 'Building project...'
  displayName: 'Build'

# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

- script: |
      git remote add azure https://meezulawot.visualstudio.com/TestProject/_git/TestProjectAzureDevOps.git
      git pull origin main
      git push azure main
    displayName: 'Sync changes with Azure repository'
